dns:
  enabled: true
  bind_addr: 0.0.0.0:5053
  analysis_ip: 192.168.117.128
  check_liveness: true
  upstream_dns: 9.9.9.9:53
  spoof_network: true
  default_subnet: 10.0.1.0/8
http:
  enabled: true
  bind_addr: 0.0.0.0:8080
  log_headers: false
  spoof_payload: false